### ISSUE TITLE
AttributeError: module 'pymongo' has no attribute 'collection'

### ISSUE THREAD

**Issue by siferati** [matthiasprobst/h5RDMtoolbox#10]
## Description

Importing `h5rdmtoolbox.database.mongo` as per the tutorial [database/mongo.html#insert-metadata-into-the-database](https://h5rdmtoolbox.readthedocs.io/en/latest/userguide/database/mongo.html#insert-metadata-into-the-database) results in an error.

Looking at the `h5rdmtoolbox/database/mongo.py` file seems like it's missing an `import pymongo.collection` statement at the top.
Probably better to also add `import pymongo.errors` statement since it's also used.

#### Failure

```
> import h5rdmtoolbox.database.mongo

Traceback (most recent call last):
  File "h5rdmtoolbox/database/mongo.py", line 185, in <module>
    collection: pymongo.collection.Collection,
AttributeError: module 'pymongo' has no attribute 'collection'. Did you mean: 'collation'?
```

#### Success

Problem is fixed by manually importing `pymongo.collection` beforehand

```
> import pymongo.collection
> import h5rdmtoolbox.database.mongo
```

**Comment by matthiasprobst** [comment]
Thank you for pointing out. Which python and pymongo version are you using?

**Comment by siferati** [comment]
```
python 3.10.12
h5rdmtoolbox 1.5.2
pymongo 4.10.1
```

**Comment by matthiasprobst** [comment]
Thank you! I could reproduce the error. The toolbox is/was limited to `pymongo>=4.2.0,<4.9.0`.
However, I was able to solve the problem and `pymongo` can be used with higher version now, too. See v1.6.0

**Comment by siferati** [comment]
Thanks, confirmed the issue is solved in the new release :+1:
